import React, { createContext, useContext, useState, ReactNode } from 'react';

export type SupportedLocale = 'en' | 'de' | 'es' | 'fr' | 'it' | 'pt' | 'ru' | 'ja' | 'ko' | 'zh' | 'ar' | 'hi' | 'pl';

interface LocalizationContextType {
  locale: SupportedLocale;
  setLocale: (locale: SupportedLocale) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
  getAvailableLocales: () => Array<{ code: SupportedLocale; name: string; nativeName: string }>;
}

const LocalizationContext = createContext<LocalizationContextType | undefined>(undefined);

export const useLocalization = () => {
  const context = useContext(LocalizationContext);
  if (!context) {
    throw new Error('useLocalization must be used within a LocalizationProvider');
  }
  return context;
};

// Translation keys and their values for each language
const translations: Record<SupportedLocale, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.vocabulary': 'Vocabulary',
    'nav.vocabulary.categorized': 'Categorized',
    'nav.vocabulary.custom': 'Custom',
    'nav.exercises': 'Exercises',
    'nav.exercises.all': 'All',
    'nav.exercises.gapFill': 'Gap-Fill',
    'nav.exercises.multipleChoice': 'Multiple Choice',
    'nav.exercises.translation': 'Translation',
    'nav.exercises.matching': 'Matching',
    'nav.exercises.wordFormation': 'Word Formation',
    'nav.exercises.oppositeMeaning': 'Opposite Meaning',
    'nav.exercises.sameMeaning': 'Same Meaning',
    'nav.exercises.wordDefinition': 'Word Definition',
    'nav.exercises.describePicture': 'Describe a Picture',
    'nav.exercises.grammar': 'Grammar',
    'nav.exercises.mixed': 'Mixed',
    'nav.flashcards': 'Flashcards',
    'nav.voiceConversation': 'Voice Conversation',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',

    // Common actions
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.selectAll': 'Select All',
    'common.deselectAll': 'Deselect All',
    'common.generate': 'Generate',
    'common.start': 'Start',
    'common.restart': 'Restart',
    'common.continue': 'Continue',
    'common.finish': 'Finish',
    'common.submit': 'Submit',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',

    // Authentication
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.rememberMe': 'Remember me',
    'auth.forgotPassword': 'Forgot password?',
    'auth.welcomeBack': 'Welcome Back',
    'auth.signInToAccount': 'Sign in to your account',
    'auth.createAccount': 'Create Account',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.signIn': 'Sign in',
    'auth.signUp': 'Sign up',
    'auth.demoCredentials': 'Demo credentials',
    'auth.enterEmail': 'Enter your email',
    'auth.enterPassword': 'Enter your password',
    'auth.signingIn': 'Signing In...',
    'auth.loggedInAs': 'Logged in as',

    // Dashboard
    'dashboard.welcome': 'Welcome to {language} Learning',
    'dashboard.welcomeUser': 'Welcome, {name}!',
    'dashboard.startJourney': 'Start your journey to master the {language} language with our comprehensive learning tools.',
    'dashboard.navigateUsingSidebar': 'Navigate through different sections using the sidebar menu.',
    'dashboard.totalWords': 'Total Words',
    'dashboard.favoriteWords': 'Favorite Words',
    'dashboard.wordsPracticed': 'Words Practiced',
    'dashboard.successRate': 'Success Rate',
    'dashboard.learningProgress': 'Learning Progress',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.addNewWords': 'Add New Words',
    'dashboard.expandVocabulary': 'Expand your vocabulary',
    'dashboard.startExercise': 'Start Exercise',
    'dashboard.practiceWhatLearned': 'Practice what you\'ve learned',
    'dashboard.viewProgress': 'View Progress',
    'dashboard.trackImprovement': 'Track your improvement',
    'dashboard.currentLearningPath': 'Current Learning Path',
    'dashboard.quickStart': 'Quick Start',
    'dashboard.useSidebarToAccess': 'Use the sidebar to access vocabulary, exercises, and flashcards.',
    'dashboard.learningProgressOverview': 'Your {language} learning progress overview',
    'dashboard.vocabularyWords': '{language} vocabulary words',
    'dashboard.wordsMarkedFavorite': 'Words marked as favorite',
    'dashboard.wordsWithHistory': 'Words with learning history',
    'dashboard.averageSuccessRate': 'Average exercise success rate',

    // Vocabulary
    'vocabulary.title': 'Vocabulary',
    'vocabulary.custom': 'Custom Vocabulary',
    'vocabulary.categorized': 'Categorized Vocabulary',
    'vocabulary.managePersonalCollection': 'Manage your personal vocabulary collection',
    'vocabulary.addWord': 'Add Word',
    'vocabulary.addNewWord': 'Add New Word',
    'vocabulary.targetWord': '{language} Word',
    'vocabulary.nativeWord': '{language} Translation',
    'vocabulary.categories': 'Categories',
    'vocabulary.sampleSentence': 'Sample Sentence',
    'vocabulary.searchWords': 'Search words...',
    'vocabulary.allCategories': 'All categories',
    'vocabulary.sortBy': 'Sort by',
    'vocabulary.dateAdded': 'Date Added',
    'vocabulary.learningProgress': 'Learning Progress',
    'vocabulary.lastLearned': 'Last Learned',
    'vocabulary.successRate': 'Success: {rate}%',
    'vocabulary.exercisesCount': '{count} exercises',
    'vocabulary.noSampleSentence': 'No sample sentence provided',
    'vocabulary.enterTargetWord': 'Enter {language} word',
    'vocabulary.enterNativeWord': 'Enter {language} translation',

    // Exercises
    'exercises.title': 'Exercises',
    'exercises.allExercises': 'All Exercises',
    'exercises.gapFill': 'Gap-Fill',
    'exercises.gapFillDesc': 'Fill in the blanks with correct words',
    'exercises.multipleChoice': 'Multiple Choice',
    'exercises.multipleChoiceDesc': 'Choose the correct answer from multiple options',
    'exercises.translation': 'Translation',
    'exercises.translationDesc': 'Translate between languages',
    'exercises.matching': 'Matching',
    'exercises.matchingDesc': 'Match words with their translations',
    'exercises.wordFormation': 'Word Formation',
    'exercises.wordFormationDesc': 'Practice creating words with prefixes and suffixes',
    'exercises.oppositeMeaning': 'Opposite Meaning',
    'exercises.oppositeMeaningDesc': 'Find words with opposite meanings (antonyms)',
    'exercises.sameMeaning': 'Same Meaning',
    'exercises.sameMeaningDesc': 'Find words with similar meanings (synonyms)',
    'exercises.wordDefinition': 'Word Definition',
    'exercises.wordDefinitionDesc': 'Write the word that matches the given definition',
    'exercises.describePicture': 'Describe a Picture',
    'exercises.describePictureDesc': 'Practice describing images',
    'exercises.grammar': 'Grammar',
    'exercises.grammarDesc': 'Practice grammar rules',
    'exercises.mixed': 'Mixed',
    'exercises.mixedDesc': 'Mixed exercises for comprehensive practice',
    'exercises.startExercise': 'Start Exercise',
    'exercises.checkAnswers': 'Check Answers',
    'exercises.showHint': 'Show Hint',
    'exercises.hideHint': 'Hide Hint',
    'exercises.correctAnswer': 'Correct answer:',
    'exercises.yourAnswer': 'Your answer',
    'exercises.hint': 'Hint:',
    'exercises.explanation': 'Explanation:',
    'exercises.newExercise': 'New Exercise',
    'exercises.restartExercise': 'Restart Same Exercise',
    'exercises.practiceMistakes': 'Practice Mistakes',

    // Exercise specific
    'exercises.gapFill.title': '{language} Gap-Fill Exercise',
    'exercises.gapFill.instructions': 'Fill in the blanks with the correct words.',
    'exercises.multipleChoice.title': '{language} Multiple Choice Exercise',
    'exercises.multipleChoice.instructions': 'Choose the correct answer for each question.',
    'exercises.translation.title': '{language} to {nativeLanguage} Translation',
    'exercises.translation.instructions': 'Translate the following sentences.',
    'exercises.matching.title': '{language} - {nativeLanguage} Matching',
    'exercises.matching.instructions': 'Match words with their translations.',
    'exercises.wordFormation.title': '{language} Word Formation Exercise',
    'exercises.wordFormation.instructions': 'Create new words using prefixes and suffixes',
    'exercises.oppositeMeaning.title': '{language} Opposite Meaning Exercise',
    'exercises.oppositeMeaning.instructions': 'Find the opposite meaning (antonym) for each word',
    'exercises.sameMeaning.title': '{language} Same Meaning Exercise',
    'exercises.sameMeaning.instructions': 'Find words with the same meaning (synonym) for each word',
    'exercises.wordDefinition.title': 'Word Definition Exercise',
    'exercises.wordDefinition.instructions': 'Write the word that matches each definition',

    // Vocabulary Selector
    'vocabularySelector.useExistingVocabulary': 'Use Existing Vocabulary',
    'vocabularySelector.selectCategory': 'Select a category from your vocabulary to practice with.',
    'vocabularySelector.selectCategoryPlaceholder': 'Select a category',
    'vocabularySelector.useSelectedCategory': 'Use Selected Category',
    'vocabularySelector.wordsCount': '{count} words',

    // Word Input Form
    'wordInputForm.createNewExercise': 'Create New {exerciseType} Exercise',
    'wordInputForm.addWords': 'Add up to 20 {language} words or phrases.',
    'wordInputForm.addWord': 'Add Word',
    'wordInputForm.generateExercise': 'Generate Exercise',

    // Settings
    'settings.title': 'Settings',
    'settings.languageSettings': 'Language Settings',
    'settings.appearance': 'Appearance',
    'settings.notifications': 'Notifications',
    'settings.privacy': 'Privacy & Security',
    'settings.interfaceLanguage': 'Interface Language',
    'settings.languageForMenus': 'Language for menus and buttons',
    'settings.currentInterface': 'Current interface',
    'settings.theme': 'Theme',
    'settings.chooseTheme': 'Choose your preferred theme',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.system': 'System',

    // Profile
    'profile.title': 'Profile Settings',
    'profile.personalInfo': 'Personal Information',
    'profile.profilePicture': 'Profile Picture',
    'profile.clickCameraToChange': 'Click the camera icon to change your picture',
    'profile.phone': 'Phone',
    'profile.location': 'Location',
    'profile.dateOfBirth': 'Date of Birth',
    'profile.saveChanges': 'Save Changes',

    // Toasts and messages
    'toast.exerciseGenerated': 'Exercise Generated',
    'toast.exerciseStarted': 'Exercise started!',
    'toast.exerciseCompleted': 'Exercise completed!',
    'toast.wordAdded': 'Word added!',
    'toast.wordDeleted': 'Word deleted',
    'toast.apiKeyRequired': 'API Key Required',
    'toast.configureApiKey': 'Please configure your OpenAI API key in settings.',
    'toast.noWordsFound': 'No words found',
    'toast.categoryHasNoWords': 'This category has no words. Please add some words first.',
    'toast.exerciseLoadedFromCategory': 'Using vocabulary from {category}',

    // Errors
    'error.missingInformation': 'Missing information',
    'error.fillBothWords': 'Please fill in both {targetLanguage} and {nativeLanguage} words.',
    'error.noWordsProvided': 'No words provided',
    'error.addAtLeastOneWord': 'Please add at least one word to generate an exercise.',

    // Welcome page
    'welcome.title': 'Welcome to {language} Learning',
    'welcome.subtitle': 'Start your journey to master the {language} language with our comprehensive learning tools.',
    'welcome.navigation': 'Navigate through different sections using the sidebar menu.',
    'welcome.currentPath': 'Current Learning Path',
    'welcome.quickStart': 'Quick Start',
    'welcome.sidebarAccess': 'Use the sidebar to access vocabulary, exercises, and flashcards.',
    'welcome.loggedInAs': 'Logged in as',
    'welcome.logout': 'Logout',

    // Dashboard detailed
    'dashboard.learningProgress': 'Learning Progress',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.noRecentActivity': 'No recent activity',
    'dashboard.exercisesCompleted': '{count} exercises completed',
    'dashboard.vocabularyMastery': 'Vocabulary Mastery',
    'dashboard.exerciseCompletion': 'Exercise Completion',

    // Vocabulary detailed
    'vocabulary.manageCollection': 'Manage your personal vocabulary collection',
    'vocabulary.extractWordsFromPhoto': 'Extract Words from Photo',
    'vocabulary.dropImageHere': 'Drop your image here',
    'vocabulary.chooseFromOptions': 'or choose from the options below',
    'vocabulary.chooseFile': 'Choose File',
    'vocabulary.takePhoto': 'Take Photo',
    'vocabulary.analyzeImage': 'Analyze Image',
    'vocabulary.analyzingImage': 'Analyzing Image...',
    'vocabulary.extractedWords': 'Extracted {language} Words with Suggested Categories',
    'vocabulary.suggestedCategories': 'Suggested categories',
    'vocabulary.clickToSelectCategories': 'Click to select/deselect categories for this word',
    'vocabulary.addSelectedWords': 'Add Selected Words with Categories to Vocabulary',
    'vocabulary.analysisComplete': 'Analysis complete!',
    'vocabulary.extractedWordsCount': 'Extracted {count} {language} words with suggested categories.',
    'vocabulary.invalidFileType': 'Invalid file type',
    'vocabulary.selectImageFile': 'Please select an image file.',

    // Exercises detailed
    'exercises.useExistingVocabulary': 'Use Existing Vocabulary',
    'exercises.selectCategoryDescription': 'Select {language} words from your vocabulary to practice {exerciseType} exercises.',
    'exercises.createNewExercise': 'Create New {exerciseType} Exercise',
    'exercises.addWordsDescription': 'Add up to 20 {language} words or phrases. The exercise will generate 2-4 times as many sentences with gaps.',
    'exercises.fillBlanks': 'Fill in the blanks with correct {language} words',
    'exercises.chooseCorrectAnswer': 'Choose the correct answer from multiple options',
    'exercises.translateBetweenLanguages': 'Translate between {targetLanguage} and {nativeLanguage}',
    'exercises.matchWordsTranslations': 'Match {language} words with their {nativeLanguage} translations',
    'exercises.practiceDescribingImages': 'Practice describing images in {language}',
    'exercises.practiceGrammarRules': 'Practice {language} grammar rules',
    'exercises.mixedComprehensivePractice': 'Mixed exercises for comprehensive practice',
    'exercises.createWordsWithPrefixes': 'Practice creating words with prefixes and suffixes',
    'exercises.findOppositeWords': 'Find words with opposite meanings (antonyms)',
    'exercises.findSimilarWords': 'Find words with similar meanings (synonyms)',
    'exercises.writeWordForDefinition': 'Write the word that matches the given definition',
    'exercises.previousExercises': 'Previous Exercises',
    'exercises.open': 'Open',
    'exercises.generatePDF': 'Generate PDF',
    'exercises.generating': 'Generating...',
    'exercises.downloadPDF': 'Download PDF',

    // Profile detailed
    'profile.personalInformation': 'Personal Information',
    'profile.profilePicture': 'Profile Picture',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.location': 'Location',
    'profile.dateOfBirth': 'Date of Birth',
    'profile.saveChanges': 'Save Changes',
    'profile.privacySettings': 'Privacy Settings',
    'profile.profileVisibility': 'Profile Visibility',
    'profile.whoCanSeeProfile': 'Who can see your profile',
    'profile.showLearningProgress': 'Show Learning Progress',
    'profile.displayProgressPublicly': 'Display your progress publicly',
    'profile.showAchievements': 'Show Achievements',
    'profile.displayBadgesAchievements': 'Display your badges and achievements',
    'profile.allowMessages': 'Allow Messages',
    'profile.letUsersMessage': 'Let other users send you messages',
    'profile.interfaceTheme': 'Interface & Theme',
    'profile.interfaceLanguage': 'Interface Language',
    'profile.languageForMenus': 'Language for menus and buttons',
    'profile.themePreference': 'Theme Preference',
    'profile.chooseAppearance': 'Choose your preferred appearance',
    'profile.learningGoals': 'Learning Goals',
    'profile.dailyStudyMinutes': 'Daily Study Minutes',
    'profile.weeklySessionsGoal': 'Weekly Sessions Goal',
    'profile.targetLevel': 'Target Level',
    'profile.focusAreas': 'Focus Areas',
    'profile.currentProgress': 'Current Progress',
    'profile.dailyGoalProgress': 'Daily Goal Progress',
    'profile.achievementSettings': 'Achievement Settings',
    'profile.showAchievementBadges': 'Show Achievement Badges',
    'profile.displayBadgesOnProfile': 'Display badges on your profile',
    'profile.shareAchievements': 'Share Achievements',
    'profile.autoShareAchievements': 'Automatically share new achievements',
    'profile.celebrateStreaks': 'Celebrate Streaks',
    'profile.showCelebrationsForStreaks': 'Show celebrations for learning streaks',
    'profile.passwordSecurity': 'Password & Security',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmNewPassword': 'Confirm New Password',
    'profile.changePassword': 'Change Password',
    'profile.twoFactorAuth': 'Two-Factor Authentication',
    'profile.enableTwoFactor': 'Enable Two-Factor Authentication',
    'profile.extraSecurityLayer': 'Add an extra layer of security to your account',
    'profile.twoFactorEnabled': 'Two-factor authentication is enabled. You\'ll need to enter a verification code when signing in.',
    'profile.viewRecoveryCodes': 'View Recovery Codes',
    'profile.activeSessions': 'Active Sessions',
    'profile.current': 'Current',
    'profile.endSession': 'End Session',
    'profile.backupSync': 'Backup & Sync',
    'profile.automaticBackup': 'Automatic Backup',
    'profile.autoBackupProgress': 'Automatically backup your progress',
    'profile.cloudSync': 'Cloud Sync',
    'profile.syncDataAcrossDevices': 'Sync data across all devices',
    'profile.manualBackup': 'Manual Backup',
    'profile.createBackupNow': 'Create a backup now',
    'profile.backupNow': 'Backup Now',
    'profile.lastBackup': 'Last backup: {time}',
    'profile.learningHistory': 'Learning History',
    'profile.minutes': 'minutes',
    'profile.exercises': 'exercises',
    'profile.words': 'words',
    'profile.accuracy': 'accuracy',
    'profile.viewFullHistory': 'View Full History',
    'profile.socialMediaConnections': 'Social Media Connections',
    'profile.connected': 'Connected',
    'profile.disconnect': 'Disconnect',
    'profile.connect': 'Connect',
    'profile.learningPreferences': 'Learning Preferences',
    'profile.learningReminders': 'Learning Reminders',
    'profile.progressReports': 'Progress Reports',
    'profile.soundEffects': 'Sound Effects',
    'profile.autoplayVideos': 'Autoplay Videos',
    'profile.notificationPreferences': 'Notification Preferences',
    'profile.emailNotifications': 'Email Notifications',
    'profile.receiveUpdatesViaEmail': 'Receive updates via email',
    'profile.pushNotifications': 'Push Notifications',
    'profile.receiveBrowserNotifications': 'Receive browser notifications',
    'profile.accountManagement': 'Account Management',
    'profile.exportData': 'Export Data',
    'profile.downloadLearningData': 'Download all your learning data',
    'profile.export': 'Export',
    'profile.deleteAccount': 'Delete Account',
    'profile.permanentlyDeleteAccount': 'Permanently delete your account and all data',
    'profile.delete': 'Delete',
    'profile.confirmDeleteAccount': 'Are you sure you want to delete your account?',
    'profile.deleteAccountWarning': 'This action cannot be undone. This will permanently delete your account and remove all your data from our servers.',
    'profile.yesDeleteAccount': 'Yes, delete my account',
  },

  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.dashboard': 'Dashboard',
    'nav.vocabulary': 'Vokabular',
    'nav.vocabulary.categorized': 'Kategorisiert',
    'nav.vocabulary.custom': 'Benutzerdefiniert',
    'nav.exercises': 'Übungen',
    'nav.exercises.all': 'Alle',
    'nav.exercises.gapFill': 'Lückentext',
    'nav.exercises.multipleChoice': 'Multiple Choice',
    'nav.exercises.translation': 'Übersetzung',
    'nav.exercises.matching': 'Zuordnung',
    'nav.exercises.wordFormation': 'Wortbildung',
    'nav.exercises.oppositeMeaning': 'Gegenteil',
    'nav.exercises.sameMeaning': 'Gleiche Bedeutung',
    'nav.exercises.wordDefinition': 'Wortdefinition',
    'nav.exercises.describePicture': 'Bild beschreiben',
    'nav.exercises.grammar': 'Grammatik',
    'nav.exercises.mixed': 'Gemischt',
    'nav.flashcards': 'Karteikarten',
    'nav.voiceConversation': 'Sprachkonversation',
    'nav.profile': 'Profil',
    'nav.settings': 'Einstellungen',

    // Common actions
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.add': 'Hinzufügen',
    'common.remove': 'Entfernen',
    'common.close': 'Schließen',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.previous': 'Zurück',
    'common.loading': 'Lädt...',
    'common.search': 'Suchen',
    'common.filter': 'Filter',
    'common.sort': 'Sortieren',
    'common.selectAll': 'Alle auswählen',
    'common.deselectAll': 'Alle abwählen',
    'common.generate': 'Generieren',
    'common.start': 'Starten',
    'common.restart': 'Neu starten',
    'common.continue': 'Fortfahren',
    'common.finish': 'Beenden',
    'common.submit': 'Absenden',
    'common.confirm': 'Bestätigen',
    'common.yes': 'Ja',
    'common.no': 'Nein',

    // Authentication
    'auth.login': 'Anmelden',
    'auth.logout': 'Abmelden',
    'auth.register': 'Registrieren',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.confirmPassword': 'Passwort bestätigen',
    'auth.firstName': 'Vorname',
    'auth.lastName': 'Nachname',
    'auth.rememberMe': 'Angemeldet bleiben',
    'auth.forgotPassword': 'Passwort vergessen?',
    'auth.welcomeBack': 'Willkommen zurück',
    'auth.signInToAccount': 'Melden Sie sich in Ihrem Konto an',
    'auth.createAccount': 'Konto erstellen',
    'auth.alreadyHaveAccount': 'Haben Sie bereits ein Konto?',
    'auth.dontHaveAccount': 'Haben Sie noch kein Konto?',
    'auth.signIn': 'Anmelden',
    'auth.signUp': 'Registrieren',
    'auth.demoCredentials': 'Demo-Anmeldedaten',
    'auth.enterEmail': 'E-Mail eingeben',
    'auth.enterPassword': 'Passwort eingeben',
    'auth.signingIn': 'Anmelden...',
    'auth.loggedInAs': 'Angemeldet als',

    // Dashboard
    'dashboard.welcome': 'Willkommen zum {language} Lernen',
    'dashboard.welcomeUser': 'Willkommen, {name}!',
    'dashboard.startJourney': 'Beginnen Sie Ihre Reise, um die {language} Sprache mit unseren umfassenden Lerntools zu meistern.',
    'dashboard.navigateUsingSidebar': 'Navigieren Sie durch verschiedene Bereiche mit dem Seitenmenü.',
    'dashboard.totalWords': 'Gesamte Wörter',
    'dashboard.favoriteWords': 'Lieblingswörter',
    'dashboard.wordsPracticed': 'Geübte Wörter',
    'dashboard.successRate': 'Erfolgsrate',
    'dashboard.learningProgress': 'Lernfortschritt',
    'dashboard.recentActivity': 'Letzte Aktivität',
    'dashboard.quickActions': 'Schnellaktionen',
    'dashboard.addNewWords': 'Neue Wörter hinzufügen',
    'dashboard.expandVocabulary': 'Erweitern Sie Ihren Wortschatz',
    'dashboard.startExercise': 'Übung starten',
    'dashboard.practiceWhatLearned': 'Üben Sie das Gelernte',
    'dashboard.viewProgress': 'Fortschritt anzeigen',
    'dashboard.trackImprovement': 'Verfolgen Sie Ihre Verbesserung',
    'dashboard.currentLearningPath': 'Aktueller Lernpfad',
    'dashboard.quickStart': 'Schnellstart',
    'dashboard.useSidebarToAccess': 'Verwenden Sie die Seitenleiste, um auf Vokabular, Übungen und Karteikarten zuzugreifen.',
    'dashboard.learningProgressOverview': 'Ihr {language} Lernfortschritt-Überblick',
    'dashboard.vocabularyWords': '{language} Vokabelwörter',
    'dashboard.wordsMarkedFavorite': 'Als Favorit markierte Wörter',
    'dashboard.wordsWithHistory': 'Wörter mit Lernhistorie',
    'dashboard.averageSuccessRate': 'Durchschnittliche Erfolgsrate bei Übungen',

    // Vocabulary
    'vocabulary.title': 'Vokabular',
    'vocabulary.custom': 'Benutzerdefiniertes Vokabular',
    'vocabulary.categorized': 'Kategorisiertes Vokabular',
    'vocabulary.managePersonalCollection': 'Verwalten Sie Ihre persönliche Vokabelsammlung',
    'vocabulary.addWord': 'Wort hinzufügen',
    'vocabulary.addNewWord': 'Neues Wort hinzufügen',
    'vocabulary.targetWord': '{language} Wort',
    'vocabulary.nativeWord': '{language} Übersetzung',
    'vocabulary.categories': 'Kategorien',
    'vocabulary.sampleSentence': 'Beispielsatz',
    'vocabulary.searchWords': 'Wörter suchen...',
    'vocabulary.allCategories': 'Alle Kategorien',
    'vocabulary.sortBy': 'Sortieren nach',
    'vocabulary.dateAdded': 'Hinzugefügt am',
    'vocabulary.learningProgress': 'Lernfortschritt',
    'vocabulary.lastLearned': 'Zuletzt gelernt',
    'vocabulary.successRate': 'Erfolg: {rate}%',
    'vocabulary.exercisesCount': '{count} Übungen',
    'vocabulary.noSampleSentence': 'Kein Beispielsatz vorhanden',
    'vocabulary.enterTargetWord': '{language} Wort eingeben',
    'vocabulary.enterNativeWord': '{language} Übersetzung eingeben',

    // Exercises
    'exercises.title': 'Übungen',
    'exercises.allExercises': 'Alle Übungen',
    'exercises.gapFill': 'Lückentext',
    'exercises.gapFillDesc': 'Füllen Sie die Lücken mit den richtigen Wörtern',
    'exercises.multipleChoice': 'Multiple Choice',
    'exercises.multipleChoiceDesc': 'Wählen Sie die richtige Antwort aus mehreren Optionen',
    'exercises.translation': 'Übersetzung',
    'exercises.translationDesc': 'Übersetzen Sie zwischen Sprachen',
    'exercises.matching': 'Zuordnung',
    'exercises.matchingDesc': 'Ordnen Sie Wörter ihren Übersetzungen zu',
    'exercises.wordFormation': 'Wortbildung',
    'exercises.wordFormationDesc': 'Üben Sie das Erstellen von Wörtern mit Präfixen und Suffixen',
    'exercises.oppositeMeaning': 'Gegenteil',
    'exercises.oppositeMeaningDesc': 'Finden Sie Wörter mit entgegengesetzter Bedeutung (Antonyme)',
    'exercises.sameMeaning': 'Gleiche Bedeutung',
    'exercises.sameMeaningDesc': 'Finden Sie Wörter mit ähnlicher Bedeutung (Synonyme)',
    'exercises.wordDefinition': 'Wortdefinition',
    'exercises.wordDefinitionDesc': 'Schreiben Sie das Wort, das zur gegebenen Definition passt',
    'exercises.describePicture': 'Bild beschreiben',
    'exercises.describePictureDesc': 'Üben Sie das Beschreiben von Bildern',
    'exercises.grammar': 'Grammatik',
    'exercises.grammarDesc': 'Üben Sie Grammatikregeln',
    'exercises.mixed': 'Gemischt',
    'exercises.mixedDesc': 'Gemischte Übungen für umfassendes Üben',
    'exercises.startExercise': 'Übung starten',
    'exercises.checkAnswers': 'Antworten überprüfen',
    'exercises.showHint': 'Hinweis anzeigen',
    'exercises.hideHint': 'Hinweis ausblenden',
    'exercises.correctAnswer': 'Richtige Antwort:',
    'exercises.yourAnswer': 'Ihre Antwort',
    'exercises.hint': 'Hinweis:',
    'exercises.explanation': 'Erklärung:',
    'exercises.newExercise': 'Neue Übung',
    'exercises.restartExercise': 'Gleiche Übung wiederholen',
    'exercises.practiceMistakes': 'Fehler üben',

    // Exercise specific
    'exercises.gapFill.title': '{language} Lückentext-Übung',
    'exercises.gapFill.instructions': 'Füllen Sie die Lücken mit den richtigen Wörtern.',
    'exercises.multipleChoice.title': '{language} Multiple Choice Übung',
    'exercises.multipleChoice.instructions': 'Wählen Sie die richtige Antwort für jede Frage.',
    'exercises.translation.title': '{language} zu {nativeLanguage} Übersetzung',
    'exercises.translation.instructions': 'Übersetzen Sie die folgenden Sätze.',
    'exercises.matching.title': '{language} - {nativeLanguage} Zuordnung',
    'exercises.matching.instructions': 'Ordnen Sie Wörter ihren Übersetzungen zu.',
    'exercises.wordFormation.title': '{language} Wortbildungs-Übung',
    'exercises.wordFormation.instructions': 'Erstellen Sie neue Wörter mit Präfixen und Suffixen',
    'exercises.oppositeMeaning.title': '{language} Gegenteil-Übung',
    'exercises.oppositeMeaning.instructions': 'Finden Sie die entgegengesetzte Bedeutung (Antonym) für jedes Wort',
    'exercises.sameMeaning.title': '{language} Gleiche Bedeutung-Übung',
    'exercises.sameMeaning.instructions': 'Finden Sie Wörter mit der gleichen Bedeutung (Synonym) für jedes Wort',
    'exercises.wordDefinition.title': 'Wortdefinitions-Übung',
    'exercises.wordDefinition.instructions': 'Schreiben Sie das Wort, das zu jeder Definition passt',

    // Vocabulary Selector
    'vocabularySelector.useExistingVocabulary': 'Vorhandenes Vokabular verwenden',
    'vocabularySelector.selectCategory': 'Wählen Sie eine Kategorie aus Ihrem Vokabular zum Üben.',
    'vocabularySelector.selectCategoryPlaceholder': 'Kategorie auswählen',
    'vocabularySelector.useSelectedCategory': 'Ausgewählte Kategorie verwenden',
    'vocabularySelector.wordsCount': '{count} Wörter',

    // Word Input Form
    'wordInputForm.createNewExercise': 'Neue {exerciseType} Übung erstellen',
    'wordInputForm.addWords': 'Fügen Sie bis zu 20 {language} Wörter oder Phrasen hinzu.',
    'wordInputForm.addWord': 'Wort hinzufügen',
    'wordInputForm.generateExercise': 'Übung generieren',

    // Settings
    'settings.title': 'Einstellungen',
    'settings.languageSettings': 'Spracheinstellungen',
    'settings.appearance': 'Erscheinungsbild',
    'settings.notifications': 'Benachrichtigungen',
    'settings.privacy': 'Datenschutz & Sicherheit',
    'settings.interfaceLanguage': 'Oberflächensprache',
    'settings.languageForMenus': 'Sprache für Menüs und Schaltflächen',
    'settings.currentInterface': 'Aktuelle Oberfläche',
    'settings.theme': 'Design',
    'settings.chooseTheme': 'Wählen Sie Ihr bevorzugtes Design',
    'settings.light': 'Hell',
    'settings.dark': 'Dunkel',
    'settings.system': 'System',

    // Profile
    'profile.title': 'Profil-Einstellungen',
    'profile.personalInfo': 'Persönliche Informationen',
    'profile.profilePicture': 'Profilbild',
    'profile.clickCameraToChange': 'Klicken Sie auf das Kamera-Symbol, um Ihr Bild zu ändern',
    'profile.phone': 'Telefon',
    'profile.location': 'Standort',
    'profile.dateOfBirth': 'Geburtsdatum',
    'profile.saveChanges': 'Änderungen speichern',

    // Toasts and messages
    'toast.exerciseGenerated': 'Übung generiert',
    'toast.exerciseStarted': 'Übung gestartet!',
    'toast.exerciseCompleted': 'Übung abgeschlossen!',
    'toast.wordAdded': 'Wort hinzugefügt!',
    'toast.wordDeleted': 'Wort gelöscht',
    'toast.apiKeyRequired': 'API-Schlüssel erforderlich',
    'toast.configureApiKey': 'Bitte konfigurieren Sie Ihren OpenAI API-Schlüssel in den Einstellungen.',
    'toast.noWordsFound': 'Keine Wörter gefunden',
    'toast.categoryHasNoWords': 'Diese Kategorie hat keine Wörter. Bitte fügen Sie zuerst einige Wörter hinzu.',
    'toast.exerciseLoadedFromCategory': 'Verwende Vokabular aus {category}',

    // Errors
    'error.missingInformation': 'Fehlende Informationen',
    'error.fillBothWords': 'Bitte füllen Sie sowohl {targetLanguage} als auch {nativeLanguage} Wörter aus.',
    'error.noWordsProvided': 'Keine Wörter angegeben',
    'error.addAtLeastOneWord': 'Bitte fügen Sie mindestens ein Wort hinzu, um eine Übung zu generieren.',

    // Welcome page
    'welcome.title': 'Willkommen zum {language} Lernen',
    'welcome.subtitle': 'Beginnen Sie Ihre Reise, um die {language} Sprache mit unseren umfassenden Lerntools zu meistern.',
    'welcome.navigation': 'Navigieren Sie durch verschiedene Bereiche mit dem Seitenmenü.',
    'welcome.currentPath': 'Aktueller Lernpfad',
    'welcome.quickStart': 'Schnellstart',
    'welcome.sidebarAccess': 'Verwenden Sie die Seitenleiste, um auf Vokabular, Übungen und Karteikarten zuzugreifen.',
    'welcome.loggedInAs': 'Angemeldet als',
    'welcome.logout': 'Abmelden',

    // Dashboard detailed
    'dashboard.learningProgress': 'Lernfortschritt',
    'dashboard.recentActivity': 'Letzte Aktivität',
    'dashboard.noRecentActivity': 'Keine aktuelle Aktivität',
    'dashboard.exercisesCompleted': '{count} Übungen abgeschlossen',
    'dashboard.vocabularyMastery': 'Vokabel-Beherrschung',
    'dashboard.exerciseCompletion': 'Übungsabschluss',

    // Vocabulary detailed
    'vocabulary.manageCollection': 'Verwalten Sie Ihre persönliche Vokabelsammlung',
    'vocabulary.extractWordsFromPhoto': 'Wörter aus Foto extrahieren',
    'vocabulary.dropImageHere': 'Bild hier ablegen',
    'vocabulary.chooseFromOptions': 'oder aus den folgenden Optionen wählen',
    'vocabulary.chooseFile': 'Datei auswählen',
    'vocabulary.takePhoto': 'Foto aufnehmen',
    'vocabulary.analyzeImage': 'Bild analysieren',
    'vocabulary.analyzingImage': 'Bild wird analysiert...',
    'vocabulary.extractedWords': 'Extrahierte {language} Wörter mit vorgeschlagenen Kategorien',
    'vocabulary.suggestedCategories': 'Vorgeschlagene Kategorien',
    'vocabulary.clickToSelectCategories': 'Klicken Sie, um Kategorien für dieses Wort auszuwählen/abzuwählen',
    'vocabulary.addSelectedWords': 'Ausgewählte Wörter mit Kategorien zum Vokabular hinzufügen',
    'vocabulary.analysisComplete': 'Analyse abgeschlossen!',
    'vocabulary.extractedWordsCount': '{count} {language} Wörter mit vorgeschlagenen Kategorien extrahiert.',
    'vocabulary.invalidFileType': 'Ungültiger Dateityp',
    'vocabulary.selectImageFile': 'Bitte wählen Sie eine Bilddatei aus.',

    // Exercises detailed
    'exercises.useExistingVocabulary': 'Vorhandenes Vokabular verwenden',
    'exercises.selectCategoryDescription': 'Wählen Sie {language} Wörter aus Ihrem Vokabular, um {exerciseType} Übungen zu üben.',
    'exercises.createNewExercise': 'Neue {exerciseType} Übung erstellen',
    'exercises.addWordsDescription': 'Fügen Sie bis zu 20 {language} Wörter oder Phrasen hinzu. Die Übung generiert 2-4 mal so viele Sätze mit Lücken.',
    'exercises.fillBlanks': 'Füllen Sie die Lücken mit korrekten {language} Wörtern',
    'exercises.chooseCorrectAnswer': 'Wählen Sie die richtige Antwort aus mehreren Optionen',
    'exercises.translateBetweenLanguages': 'Übersetzen Sie zwischen {targetLanguage} und {nativeLanguage}',
    'exercises.matchWordsTranslations': 'Ordnen Sie {language} Wörter ihren {nativeLanguage} Übersetzungen zu',
    'exercises.practiceDescribingImages': 'Üben Sie das Beschreiben von Bildern auf {language}',
    'exercises.practiceGrammarRules': 'Üben Sie {language} Grammatikregeln',
    'exercises.mixedComprehensivePractice': 'Gemischte Übungen für umfassendes Üben',
    'exercises.createWordsWithPrefixes': 'Üben Sie das Erstellen von Wörtern mit Präfixen und Suffixen',
    'exercises.findOppositeWords': 'Finden Sie Wörter mit entgegengesetzter Bedeutung (Antonyme)',
    'exercises.findSimilarWords': 'Finden Sie Wörter mit ähnlicher Bedeutung (Synonyme)',
    'exercises.writeWordForDefinition': 'Schreiben Sie das Wort, das zur gegebenen Definition passt',
    'exercises.previousExercises': 'Vorherige Übungen',
    'exercises.open': 'Öffnen',
    'exercises.generatePDF': 'PDF generieren',
    'exercises.generating': 'Generiere...',
    'exercises.downloadPDF': 'PDF herunterladen',

    // Profile detailed
    'profile.personalInformation': 'Persönliche Informationen',
    'profile.profilePicture': 'Profilbild',
    'profile.firstName': 'Vorname',
    'profile.lastName': 'Nachname',
    'profile.email': 'E-Mail',
    'profile.phone': 'Telefon',
    'profile.location': 'Standort',
    'profile.dateOfBirth': 'Geburtsdatum',
    'profile.saveChanges': 'Änderungen speichern',
    'profile.privacySettings': 'Datenschutzeinstellungen',
    'profile.profileVisibility': 'Profil-Sichtbarkeit',
    'profile.whoCanSeeProfile': 'Wer kann Ihr Profil sehen',
    'profile.showLearningProgress': 'Lernfortschritt anzeigen',
    'profile.displayProgressPublicly': 'Zeigen Sie Ihren Fortschritt öffentlich an',
    'profile.showAchievements': 'Erfolge anzeigen',
    'profile.displayBadgesAchievements': 'Zeigen Sie Ihre Abzeichen und Erfolge an',
    'profile.allowMessages': 'Nachrichten erlauben',
    'profile.letUsersMessage': 'Lassen Sie andere Benutzer Ihnen Nachrichten senden',
    'profile.interfaceTheme': 'Oberfläche & Design',
    'profile.interfaceLanguage': 'Oberflächensprache',
    'profile.languageForMenus': 'Sprache für Menüs und Schaltflächen',
    'profile.themePreference': 'Design-Präferenz',
    'profile.chooseAppearance': 'Wählen Sie Ihr bevorzugtes Erscheinungsbild',
    'profile.learningGoals': 'Lernziele',
    'profile.dailyStudyMinutes': 'Tägliche Lernminuten',
    'profile.weeklySessionsGoal': 'Wöchentliches Sitzungsziel',
    'profile.targetLevel': 'Zielniveau',
    'profile.focusAreas': 'Schwerpunktbereiche',
    'profile.currentProgress': 'Aktueller Fortschritt',
    'profile.dailyGoalProgress': 'Täglicher Zielfortschritt',
    'profile.achievementSettings': 'Erfolgseinstellungen',
    'profile.showAchievementBadges': 'Erfolgsabzeichen anzeigen',
    'profile.displayBadgesOnProfile': 'Zeigen Sie Abzeichen in Ihrem Profil an',
    'profile.shareAchievements': 'Erfolge teilen',
    'profile.autoShareAchievements': 'Neue Erfolge automatisch teilen',
    'profile.celebrateStreaks': 'Serien feiern',
    'profile.showCelebrationsForStreaks': 'Zeigen Sie Feiern für Lernserien',
    'profile.passwordSecurity': 'Passwort & Sicherheit',
    'profile.currentPassword': 'Aktuelles Passwort',
    'profile.newPassword': 'Neues Passwort',
    'profile.confirmNewPassword': 'Neues Passwort bestätigen',
    'profile.changePassword': 'Passwort ändern',
    'profile.twoFactorAuth': 'Zwei-Faktor-Authentifizierung',
    'profile.enableTwoFactor': 'Zwei-Faktor-Authentifizierung aktivieren',
    'profile.extraSecurityLayer': 'Fügen Sie eine zusätzliche Sicherheitsebene zu Ihrem Konto hinzu',
    'profile.twoFactorEnabled': 'Zwei-Faktor-Authentifizierung ist aktiviert. Sie müssen einen Bestätigungscode eingeben, wenn Sie sich anmelden.',
    'profile.viewRecoveryCodes': 'Wiederherstellungscodes anzeigen',
    'profile.activeSessions': 'Aktive Sitzungen',
    'profile.current': 'Aktuell',
    'profile.endSession': 'Sitzung beenden',
    'profile.backupSync': 'Sicherung & Synchronisation',
    'profile.automaticBackup': 'Automatische Sicherung',
    'profile.autoBackupProgress': 'Sichern Sie Ihren Fortschritt automatisch',
    'profile.cloudSync': 'Cloud-Synchronisation',
    'profile.syncDataAcrossDevices': 'Daten auf allen Geräten synchronisieren',
    'profile.manualBackup': 'Manuelle Sicherung',
    'profile.createBackupNow': 'Jetzt eine Sicherung erstellen',
    'profile.backupNow': 'Jetzt sichern',
    'profile.lastBackup': 'Letzte Sicherung: {time}',
    'profile.learningHistory': 'Lernhistorie',
    'profile.minutes': 'Minuten',
    'profile.exercises': 'Übungen',
    'profile.words': 'Wörter',
    'profile.accuracy': 'Genauigkeit',
    'profile.viewFullHistory': 'Vollständige Historie anzeigen',
    'profile.socialMediaConnections': 'Social Media Verbindungen',
    'profile.connected': 'Verbunden',
    'profile.disconnect': 'Trennen',
    'profile.connect': 'Verbinden',
    'profile.learningPreferences': 'Lernpräferenzen',
    'profile.learningReminders': 'Lernerinnerungen',
    'profile.progressReports': 'Fortschrittsberichte',
    'profile.soundEffects': 'Soundeffekte',
    'profile.autoplayVideos': 'Videos automatisch abspielen',
    'profile.notificationPreferences': 'Benachrichtigungseinstellungen',
    'profile.emailNotifications': 'E-Mail-Benachrichtigungen',
    'profile.receiveUpdatesViaEmail': 'Updates per E-Mail erhalten',
    'profile.pushNotifications': 'Push-Benachrichtigungen',
    'profile.receiveBrowserNotifications': 'Browser-Benachrichtigungen erhalten',
    'profile.accountManagement': 'Kontoverwaltung',
    'profile.exportData': 'Daten exportieren',
    'profile.downloadLearningData': 'Alle Ihre Lerndaten herunterladen',
    'profile.export': 'Exportieren',
    'profile.deleteAccount': 'Konto löschen',
    'profile.permanentlyDeleteAccount': 'Löschen Sie Ihr Konto und alle Daten dauerhaft',
    'profile.delete': 'Löschen',
    'profile.confirmDeleteAccount': 'Sind Sie sicher, dass Sie Ihr Konto löschen möchten?',
    'profile.deleteAccountWarning': 'Diese Aktion kann nicht rückgängig gemacht werden. Dadurch wird Ihr Konto dauerhaft gelöscht und alle Ihre Daten von unseren Servern entfernt.',
    'profile.yesDeleteAccount': 'Ja, mein Konto löschen',
  },

  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.dashboard': 'Panel',
    'nav.vocabulary': 'Vocabulario',
    'nav.vocabulary.categorized': 'Categorizado',
    'nav.vocabulary.custom': 'Personalizado',
    'nav.exercises': 'Ejercicios',
    'nav.exercises.all': 'Todos',
    'nav.exercises.gapFill': 'Rellenar espacios',
    'nav.exercises.multipleChoice': 'Opción múltiple',
    'nav.exercises.translation': 'Traducción',
    'nav.exercises.matching': 'Emparejar',
    'nav.exercises.wordFormation': 'Formación de palabras',
    'nav.exercises.oppositeMeaning': 'Significado opuesto',
    'nav.exercises.sameMeaning': 'Mismo significado',
    'nav.exercises.wordDefinition': 'Definición de palabra',
    'nav.exercises.describePicture': 'Describir imagen',
    'nav.exercises.grammar': 'Gramática',
    'nav.exercises.mixed': 'Mixto',
    'nav.flashcards': 'Tarjetas',
    'nav.voiceConversation': 'Conversación por voz',
    'nav.profile': 'Perfil',
    'nav.settings': 'Configuración',

    // Common actions
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.add': 'Añadir',
    'common.remove': 'Quitar',
    'common.close': 'Cerrar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.loading': 'Cargando...',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.selectAll': 'Seleccionar todo',
    'common.deselectAll': 'Deseleccionar todo',
    'common.generate': 'Generar',
    'common.start': 'Iniciar',
    'common.restart': 'Reiniciar',
    'common.continue': 'Continuar',
    'common.finish': 'Terminar',
    'common.submit': 'Enviar',
    'common.confirm': 'Confirmar',
    'common.yes': 'Sí',
    'common.no': 'No',

    // Add more Spanish translations...
    'auth.login': 'Iniciar sesión',
    'auth.logout': 'Cerrar sesión',
    'dashboard.welcome': 'Bienvenido al aprendizaje de {language}',
    'vocabulary.title': 'Vocabulario',
    'exercises.title': 'Ejercicios',
    'settings.title': 'Configuración',
    'settings.interfaceLanguage': 'Idioma de la interfaz',
    'settings.languageForMenus': 'Idioma para menús y botones',
    'settings.currentInterface': 'Interfaz actual',
    'profile.title': 'Configuración del perfil',
  },

  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.dashboard': 'Tableau de bord',
    'nav.vocabulary': 'Vocabulaire',
    'nav.exercises': 'Exercices',
    'nav.flashcards': 'Cartes mémoire',
    'nav.profile': 'Profil',
    'nav.settings': 'Paramètres',

    // Common actions
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.add': 'Ajouter',

    // Add more French translations...
    'auth.login': 'Se connecter',
    'auth.logout': 'Se déconnecter',
    'dashboard.welcome': 'Bienvenue à l\'apprentissage du {language}',
    'vocabulary.title': 'Vocabulaire',
    'exercises.title': 'Exercices',
    'settings.title': 'Paramètres',
    'settings.interfaceLanguage': 'Langue de l\'interface',
    'settings.languageForMenus': 'Langue pour les menus et boutons',
    'settings.currentInterface': 'Interface actuelle',
    'profile.title': 'Paramètres du profil',
  },

  it: {
    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Cruscotto',
    'nav.vocabulary': 'Vocabolario',
    'nav.vocabulary.categorized': 'Categorizzato',
    'nav.vocabulary.custom': 'Personalizzato',
    'nav.exercises': 'Esercizi',
    'nav.exercises.all': 'Tutti',
    'nav.exercises.gapFill': 'Riempi gli spazi',
    'nav.exercises.multipleChoice': 'Scelta multipla',
    'nav.exercises.translation': 'Traduzione',
    'nav.exercises.matching': 'Abbinamento',
    'nav.exercises.wordFormation': 'Formazione parole',
    'nav.exercises.oppositeMeaning': 'Significato opposto',
    'nav.exercises.sameMeaning': 'Stesso significato',
    'nav.exercises.wordDefinition': 'Definizione parola',
    'nav.exercises.describePicture': 'Descrivi immagine',
    'nav.exercises.grammar': 'Grammatica',
    'nav.exercises.mixed': 'Misto',
    'nav.flashcards': 'Flashcard',
    'nav.voiceConversation': 'Conversazione Vocale',
    'nav.profile': 'Profilo',
    'nav.settings': 'Impostazioni',

    // Add Italian translations...
    'auth.login': 'Accedi',
    'auth.logout': 'Esci',
    'dashboard.welcome': 'Benvenuto all\'apprendimento del {language}',
    'vocabulary.title': 'Vocabolario',
    'exercises.title': 'Esercizi',
    'exercises.main': 'Esercizi',
    'settings.title': 'Impostazioni',
    'settings.interfaceLanguage': 'Lingua dell\'interfaccia',
    'settings.languageForMenus': 'Lingua per menu e pulsanti',
    'settings.currentInterface': 'Interfaccia attuale',
    'profile.title': 'Impostazioni profilo',
  },

  pt: {
    // Add Portuguese translations...
    'nav.home': 'Início',
    'nav.dashboard': 'Painel',
    'nav.vocabulary': 'Vocabulário',
    'nav.exercises': 'Exercícios',
    'auth.login': 'Entrar',
    'auth.logout': 'Sair',
    'dashboard.welcome': 'Bem-vindo ao aprendizado de {language}',
    'vocabulary.title': 'Vocabulário',
    'exercises.title': 'Exercícios',
    'settings.title': 'Configurações',
    'profile.title': 'Configurações do perfil',
  },

  ru: {
    // Add Russian translations...
    'nav.home': 'Главная',
    'nav.dashboard': 'Панель',
    'nav.vocabulary': 'Словарь',
    'nav.exercises': 'Упражнения',
    'auth.login': 'Войти',
    'auth.logout': 'Выйти',
    'dashboard.welcome': 'Добро пожаловать в изучение {language}',
    'vocabulary.title': 'Словарь',
    'exercises.title': 'Упражнения',
    'settings.title': 'Настройки',
    'profile.title': 'Настройки профиля',
  },

  ja: {
    // Add Japanese translations...
    'nav.home': 'ホーム',
    'nav.dashboard': 'ダッシュボード',
    'nav.vocabulary': '語彙',
    'nav.exercises': '練習',
    'auth.login': 'ログイン',
    'auth.logout': 'ログアウト',
    'dashboard.welcome': '{language}学習へようこそ',
    'vocabulary.title': '語彙',
    'exercises.title': '練習',
    'settings.title': '設定',
    'profile.title': 'プロフィール設定',
  },

  ko: {
    // Add Korean translations...
    'nav.home': '홈',
    'nav.dashboard': '대시보드',
    'nav.vocabulary': '어휘',
    'nav.exercises': '연습',
    'auth.login': '로그인',
    'auth.logout': '로그아웃',
    'dashboard.welcome': '{language} 학습에 오신 것을 환영합니다',
    'vocabulary.title': '어휘',
    'exercises.title': '연습',
    'settings.title': '설정',
    'profile.title': '프로필 설정',
  },

  zh: {
    // Add Chinese translations...
    'nav.home': '首页',
    'nav.dashboard': '仪表板',
    'nav.vocabulary': '词汇',
    'nav.exercises': '练习',
    'auth.login': '登录',
    'auth.logout': '登出',
    'dashboard.welcome': '欢迎学习{language}',
    'vocabulary.title': '词汇',
    'exercises.title': '练习',
    'settings.title': '设置',
    'profile.title': '个人资料设置',
  },

  ar: {
    // Add Arabic translations...
    'nav.home': 'الرئيسية',
    'nav.dashboard': 'لوحة التحكم',
    'nav.vocabulary': 'المفردات',
    'nav.exercises': 'التمارين',
    'auth.login': 'تسجيل الدخول',
    'auth.logout': 'تسجيل الخروج',
    'dashboard.welcome': 'مرحباً بك في تعلم {language}',
    'vocabulary.title': 'المفردات',
    'exercises.title': 'التمارين',
    'settings.title': 'الإعدادات',
    'profile.title': 'إعدادات الملف الشخصي',
  },

  hi: {
    // Add Hindi translations...
    'nav.home': 'होम',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.vocabulary': 'शब्दावली',
    'nav.exercises': 'अभ्यास',
    'auth.login': 'लॉग इन',
    'auth.logout': 'लॉग आउट',
    'dashboard.welcome': '{language} सीखने में आपका स्वागत है',
    'vocabulary.title': 'शब्दावली',
    'exercises.title': 'अभ्यास',
    'settings.title': 'सेटिंग्स',
    'profile.title': 'प्रोफ़ाइल सेटिंग्स',
  },

  pl: {
    // Add Polish translations...
    'nav.home': 'Strona główna',
    'nav.dashboard': 'Panel',
    'nav.vocabulary': 'Słownictwo',
    'nav.exercises': 'Ćwiczenia',
    'auth.login': 'Zaloguj się',
    'auth.logout': 'Wyloguj się',
    'dashboard.welcome': 'Witamy w nauce {language}',
    'vocabulary.title': 'Słownictwo',
    'exercises.title': 'Ćwiczenia',
    'settings.title': 'Ustawienia',
    'profile.title': 'Ustawienia profilu',
  },
};

const AVAILABLE_LOCALES = [
  { code: 'en' as SupportedLocale, name: 'English', nativeName: 'English' },
  { code: 'de' as SupportedLocale, name: 'German', nativeName: 'Deutsch' },
  { code: 'es' as SupportedLocale, name: 'Spanish', nativeName: 'Español' },
  { code: 'fr' as SupportedLocale, name: 'French', nativeName: 'Français' },
  { code: 'it' as SupportedLocale, name: 'Italian', nativeName: 'Italiano' },
  { code: 'pt' as SupportedLocale, name: 'Portuguese', nativeName: 'Português' },
  { code: 'ru' as SupportedLocale, name: 'Russian', nativeName: 'Русский' },
  { code: 'ja' as SupportedLocale, name: 'Japanese', nativeName: '日本語' },
  { code: 'ko' as SupportedLocale, name: 'Korean', nativeName: '한국어' },
  { code: 'zh' as SupportedLocale, name: 'Chinese', nativeName: '中文' },
  { code: 'ar' as SupportedLocale, name: 'Arabic', nativeName: 'العربية' },
  { code: 'hi' as SupportedLocale, name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'pl' as SupportedLocale, name: 'Polish', nativeName: 'Polski' },
];

export const LocalizationProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [locale, setLocaleState] = useState<SupportedLocale>(() => {
    const saved = localStorage.getItem('app-locale');
    return (saved as SupportedLocale) || 'en';
  });

  const setLocale = (newLocale: SupportedLocale) => {
    setLocaleState(newLocale);
    localStorage.setItem('app-locale', newLocale);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    const translation = translations[locale]?.[key] || translations.en[key] || key;
    
    if (!params) return translation;
    
    // Replace parameters in the translation
    return Object.entries(params).reduce((text, [param, value]) => {
      return text.replace(new RegExp(`\\{${param}\\}`, 'g'), String(value));
    }, translation);
  };

  const getAvailableLocales = () => AVAILABLE_LOCALES;

  return (
    <LocalizationContext.Provider value={{ locale, setLocale, t, getAvailableLocales }}>
      {children}
    </LocalizationContext.Provider>
  );
};